INSERT INTO DEPT(DEPT_ID,DEPT_NAME) VALUES(10,'TT');
INSERT INTO DEPT(DEPT_ID,DEPT_NAME) VALUES( NULL,'TT');
INSERT INTO DEPT(DEPT_ID,DEPT_NAME) VALUES( 20,'TT');
INSERT INTO DEPT(DEPT_ID,DEPT_NAME) VALUES( A1,'TT');
INSERT INTO DEPT(DEPT_ID,DEPT_NAME) VALUES(30,'Accounts');